version: '3'

services:
  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    environment:
      FLASK_ENV: "${FLASK_ENV}"
      APP_HOST: "${APP_HOST}"
      APP_PORT: "${APP_PORT}"
      PERMITTED_REMOTES: "${PERMITTED_REMOTES}"
      DATA_FILENAME: "${DATA_FILENAME}"
      MONGODB_URI: "${MONGODB_URI}"
      MONGODB_DATABASE: "${MONGODB_DATABASE}"
      MONGODB_DATABASE_TEST: "${MONGODB_DATABASE_TEST}"
      JOBLIB_MULTIPROCESSING: 0
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - "./:/opt/app"
  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "5000:80"
    depends_on:
      - flask
  mongodb:
    image: mongo:3.6.13
    restart: always
    volumes:
      - "./mongo/db:/data/db"
    ports:
      - "27017:27017"

volumes:
  app: